import { describe, expect, it } from 'vitest'; import type { CalendarDay, CalendarProvider } from '../src/lib/calendar/types'; import { CalendarService } from '../src/lib/calendar/calendarService'; import { toTodayViewModel, unavailableToday } from '../src/viewmodels/todayViewModel'; import { toDecisionViewModel } from '../src/viewmodels/decisionViewModel'; import { parseQuery } from '../src/lib/rules/queryParser';
const makeDay = (overrides: Partial<CalendarDay> = {}): CalendarDay => ({ date: '2026-08-29', weekday: '星期六', lunar: { month: '七月小', day: '十七', display: '丙午年 七月小十七' }, good: ['祭祀'], bad: ['理髮'], deityBirthdays: ['觀世音菩薩成道日'], sources: ['LunarData'], primarySource: 'LunarData', verificationSources: [], hasConflict: false, ...overrides });
const provider = (name: string, day: CalendarDay): CalendarProvider => ({ name, getDay: () => day });
describe('phase 2 integration', () => {
  it('maps CalendarDay to a real TodayViewModel', () => expect(toTodayViewModel(makeDay())).toMatchObject({ state: 'success', sourceStatus: 'real', date: { iso: '2026-08-29' }, badActions: [{ label: '理髮' }] }));
  it('uses primary decision while recording secondary conflict', async () => { const primary = makeDay(); const secondary = makeDay({ good: ['理发'], bad: [], primarySource: 'lunar-javascript', sources: ['lunar-javascript'] }); const day = await new CalendarService(provider('primary', primary), [provider('verify', secondary)]).getDay(primary.date); expect(day?.hasConflict).toBe(true); expect(toDecisionViewModel('HAIRCUT', '今天可以剪頭髮嗎', day)).toMatchObject({ status: 'not_recommended', primarySource: 'LunarData', hasConflict: true }); });
  it('failure state never returns a mock date', () => { const vm = unavailableToday('2026-08-29'); expect(vm.sourceStatus).toBe('unavailable'); expect(vm.date.solarDisplay).toBe('2026-08-29'); expect(vm.date.solarDisplay).not.toContain('2025'); });
  it('parses UI search into a ready decision', () => { const parsed = parseQuery('今天可以剪頭髮嗎', { baseDate: '2026-08-29' }); expect(toDecisionViewModel(parsed.intent!, parsed.query, makeDay())).toMatchObject({ status: 'not_recommended', needsAI: false }); });
  it('connects a calendar birthday to deity metadata', () => expect(toTodayViewModel(makeDay()).deityBirthdays[0]).toMatchObject({ id: 'guanyin', dataStatus: 'sample' }));
});
