import React, { useEffect, useState } from 'react';
import { ArrowLeft, CheckCircle2, HelpCircle, Search, ShieldAlert, XCircle } from 'lucide-react';
import type { CalendarDay } from '../src/lib/calendar/types';
import type { Intent } from '../src/lib/rules/intents';
import { parseQuery } from '../src/lib/rules/queryParser';
import { calendarService } from '../src/services/appServices';
import { toDecisionViewModel } from '../src/viewmodels/decisionViewModel';
import type { DecisionViewModel } from '../src/viewmodels/types';
const choices: { id: string; label: string; query: string; intent: Intent }[] = [{ id: 'haircut', label: '剪頭髮', query: '今天可以剪頭髮嗎？', intent: 'HAIRCUT' }, { id: 'moving', label: '搬家', query: '今天適合搬家嗎？', intent: 'MOVE_HOME' }, { id: 'worship-praying', label: '拜拜', query: '今天可以拜拜嗎？', intent: 'WORSHIP' }, { id: 'opening', label: '開工', query: '今天適合開工嗎？', intent: 'START_WORK' }];
export function RealDecisionView({ selectedId, initialQuery, today, onBack }: { selectedId: string; initialQuery?: string; today?: CalendarDay; onBack: () => void }) {
  const selected = choices.find(item => item.id === selectedId) ?? choices[0]; const [query, setQuery] = useState(initialQuery ?? selected.query); const [result, setResult] = useState<DecisionViewModel>(); const [unsupported, setUnsupported] = useState(false);
  const run = async (text: string) => { const parsed = parseQuery(text, { baseDate: today?.date }); if (!parsed.intent) { setUnsupported(true); setResult(undefined); return; } setUnsupported(false); const day = parsed.date === today?.date ? today : await calendarService.getDay(parsed.date) ?? undefined; setResult(toDecisionViewModel(parsed.intent, text, day ?? null)); };
  useEffect(() => { const text = initialQuery ?? selected.query; setQuery(text); void run(text); }, [selectedId, initialQuery, today?.date]);
  const tone = result?.status === 'recommended' ? 'text-[#2E7D32] bg-[#EBF5ED]' : result?.status === 'not_recommended' ? 'text-[#A63A28] bg-[#FDF2F0]' : 'text-[#5C554E] bg-[#F2EFE9]';
  return <div className="space-y-4 pb-12"><div className="bg-[#FDF9F3] rounded-2xl p-4 border border-[#E8E1D5]"><div className="flex items-center gap-2"><button onClick={onBack} className="p-2 rounded-lg bg-white border border-[#E8E1D5]"><ArrowLeft className="w-4 h-4"/></button><h1 className="font-serif-tc font-bold text-xl">生活決策速查</h1></div><div className="flex gap-2 overflow-x-auto mt-3">{choices.map(item => <button key={item.id} onClick={() => { setQuery(item.query); void run(item.query); }} className="shrink-0 px-3 py-2 rounded-xl bg-white border border-[#E8E1D5] text-sm">{item.label}</button>)}</div></div><form onSubmit={e => { e.preventDefault(); void run(query); }} className="bg-[#FDF9F3] rounded-2xl p-4 border border-[#E8E1D5] flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-[#736B63]"/><input value={query} onChange={e => setQuery(e.target.value)} className="w-full pl-9 pr-3 py-3 rounded-xl border border-[#E8E1D5] text-sm"/></div><button className="px-4 rounded-xl bg-[#2C2C2C] text-white">查詢</button></form>{unsupported ? <div className="bg-[#FDF9F3] rounded-2xl p-6 border border-[#E8E1D5]"><HelpCircle className="w-7 h-7 text-[#A63A28]"/><h2 className="font-bold mt-2">這個問題目前還不支援</h2><p className="text-sm text-[#736B63] mt-1">目前可查：剪頭髮、搬家、拜拜、開工。</p></div> : result && <div className="bg-[#FDF9F3] rounded-2xl p-6 border border-[#E8E1D5] shadow-sm"><div className={`inline-flex items-center gap-2 px-4 py-3 rounded-2xl font-serif-tc font-bold text-xl ${tone}`}>{result.status === 'recommended' ? <CheckCircle2/> : result.status === 'not_recommended' ? <XCircle/> : <ShieldAlert/>}{result.headline}</div><p className="mt-4 text-[#2C2C2C]">{result.explanation}</p><div className="mt-4 pt-3 border-t text-xs text-[#736B63]">判斷基準：{result.primarySource}。{result.verificationSources.length ? `驗證來源：${result.verificationSources.join('、')}。` : ''}{result.hasConflict ? '來源間存在不同說法，但未混合判定。' : ''}</div></div>}</div>;
}
